#!/usr/bin/bash
PROJECT="$(pwd)"
echo Version what you want?
read version
if [ "$1" == 'revert' ]
then
    echo Revert action to "$version"
else
    echo Branch what you want?
    read branch
    if [ -z branch ]
    then
        branch='master'
    else
        branch="$branch"
    fi
    cd "$PROJECT"/release/master && git checkout "$branch" && git pull --rebase origin "$branch"
    cd "$PROJECT"
    cp -R "$PROJECT"/release/master "$PROJECT"/release/"$version"
    cd "$PROJECT"/release/"$version" && rm -rf .git .nuxt node_modules ecosystem.config.js
    npm ci
    npm run build
    cd "$PROJECT"
fi
rm current
ln -s "$PROJECT"/release/"$version" "$PROJECT"/current
pm2 startOrReload ecosystem.config.js